Repository 2025-order-management-platform/order-management-platform-backend, pull requests merged in 2025-02, with the labels that each got.

#2 Feat/create base entity
  src/main/java/com/nineteen/omp/global/config/JpaAuditingConfig.java
  src/main/java/com/nineteen/omp/global/entity/BaseEntity.java
  src/test/java/com/nineteen/omp/global/entity/BaseEntityTest.java
Labels: feat

#3 Feat/apply query dsl
  build.gradle
  src/main/java/com/nineteen/omp/global/config/QueryDslConfig.java
  src/test/java/com/nineteen/omp/global/entity/BaseEntityTest.java
Labels: feat

#4 Feat/create common response
  src/main/java/com/nineteen/omp/global/dto/ResponseDto.java
  src/main/java/com/nineteen/omp/global/dto/ResponseMessage.java
Labels: feat

#5 Feat/apply global exception handler
  src/main/java/com/nineteen/omp/global/exception/CommonExceptionCode.java
  src/main/java/com/nineteen/omp/global/exception/CustomException.java
  src/main/java/com/nineteen/omp/global/exception/ExceptionCode.java
  src/main/java/com/nineteen/omp/global/exception/GlobalExceptionHandler.java
Labels: feat

#6 [Feat]: 기본 엔티티 생성 (PK, FK 관계 설정)
  src/main/java/com/nineteen/omp/category/domain/StoreCategory.java
  src/main/java/com/nineteen/omp/coupon/domain/Coupon.java
  src/main/java/com/nineteen/omp/coupon/domain/UserCoupon.java
  src/main/java/com/nineteen/omp/order/domain/Delivery.java
  src/main/java/com/nineteen/omp/order/domain/Order.java
  src/main/java/com/nineteen/omp/order/domain/OrderProduct.java
  src/main/java/com/nineteen/omp/order/domain/OrderReview.java
  src/main/java/com/nineteen/omp/payment/domain/Payment.java
  src/main/java/com/nineteen/omp/product/domain/Product.java
  src/main/java/com/nineteen/omp/store/domain/Area.java
  src/main/java/com/nineteen/omp/store/domain/ServiceArea.java
  src/main/java/com/nineteen/omp/store/domain/Store.java
  src/main/java/com/nineteen/omp/store/domain/StoreProduct.java
  src/main/java/com/nineteen/omp/user/domain/User.java
Labels: feat

#10 Feat/generate jwt when login success
  build.gradle
  src/main/java/com/nineteen/omp/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/nineteen/omp/auth/jwt/JwtHeaderHandler.java
  src/main/java/com/nineteen/omp/auth/jwt/JwtProvider.java
  src/main/java/com/nineteen/omp/auth/jwt/entity/RefreshToken.java
  src/main/java/com/nineteen/omp/auth/jwt/repository/RefreshRepository.java
  src/main/java/com/nineteen/omp/auth/jwt/service/RefreshService.java
  src/main/java/com/nineteen/omp/auth/jwt/service/RefreshServiceImpl.java
  src/main/java/com/nineteen/omp/global/config/EmbeddedRedisConfig.java
  src/main/java/com/nineteen/omp/global/config/RedisConfig.java
  src/test/java/com/nineteen/omp/auth/handler/CustomAuthenticationSuccessHandlerTest.java
  src/test/java/com/nineteen/omp/auth/jwt/JwtProviderTest.java
  src/test/java/com/nineteen/omp/auth/jwt/repository/RefreshRepositoryTest.java
Labels: feat

#13 Feat/add jwt filter
  src/main/java/com/nineteen/omp/auth/filter/JwtFilter.java
  src/main/java/com/nineteen/omp/user/repository/UserRepository.java
  src/test/java/com/nineteen/omp/auth/filter/JwtFilterTest.java
Labels: feat

#14 Feat/add reissue and logout
  src/main/java/com/nineteen/omp/auth/controller/AuthController.java
  src/main/java/com/nineteen/omp/auth/exception/AuthExceptionCode.java
  src/main/java/com/nineteen/omp/auth/service/AuthService.java
  src/main/java/com/nineteen/omp/auth/service/AuthServiceImpl.java
  src/test/java/com/nineteen/omp/auth/service/AuthServiceImplTest.java
Labels: feat

#15 HOTFIX/Soft delete를 검증하는 테스트 코드 추가
  src/main/java/com/nineteen/omp/global/entity/BaseEntity.java
  src/test/java/com/nineteen/omp/global/entity/BaseEntityTest.java
Labels: bug

#7 Feat: 회원가입 기능
  build.gradle
  src/main/java/com/nineteen/omp/auth/config/SecurityConfig.java
  src/main/java/com/nineteen/omp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/controller/dto/SignupRequestDto.java
  src/main/java/com/nineteen/omp/user/domain/User.java
  src/main/java/com/nineteen/omp/user/domain/UserExceptionCode.java
  src/main/java/com/nineteen/omp/user/repository/UserRepository.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
Labels: feat, draft

#18 Feat/update payments
  src/main/java/com/nineteen/omp/payment/controller/PaymentController.java
  src/main/java/com/nineteen/omp/payment/domain/Payment.java
  src/main/java/com/nineteen/omp/payment/domain/PaymentStatus.java
  src/main/java/com/nineteen/omp/payment/exception/PaymentExceptionCode.java
  src/main/java/com/nineteen/omp/payment/service/PaymentService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentServiceImpl.java
  src/test/java/com/nineteen/omp/payment/service/PaymentServiceImplTest.java
Labels: feat

#19 Feat/get payments by order
  src/main/java/com/nineteen/omp/coupon/domain/UserCoupon.java
  src/main/java/com/nineteen/omp/payment/controller/PaymentController.java
  src/main/java/com/nineteen/omp/payment/controller/dto/GetPaymentResponseDto.java
  src/main/java/com/nineteen/omp/payment/domain/Payment.java
  src/main/java/com/nineteen/omp/payment/repository/PaymentRepository.java
  src/main/java/com/nineteen/omp/payment/service/PaymentService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentServiceImpl.java
  src/main/java/com/nineteen/omp/payment/service/dto/GetPaymentResponseCommand.java
  src/test/java/com/nineteen/omp/payment/service/PaymentServiceImplTest.java
Labels: feat

#23 Feat/search payments by user
  src/main/java/com/nineteen/omp/payment/controller/PaymentController.java
  src/main/java/com/nineteen/omp/payment/controller/dto/GetPaymentListResponseDto.java
  src/main/java/com/nineteen/omp/payment/domain/Payment.java
  src/main/java/com/nineteen/omp/payment/repository/PaymentRepository.java
  src/main/java/com/nineteen/omp/payment/service/PaymentService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentServiceImpl.java
  src/main/java/com/nineteen/omp/payment/service/dto/GetPaymentListResponseCommand.java
  src/test/java/com/nineteen/omp/payment/repository/PaymentRepositoryTest.java
  src/test/java/com/nineteen/omp/payment/service/PaymentServiceImplTest.java
Labels: feat

#25 Feat/find all payments
  src/main/java/com/nineteen/omp/payment/controller/PaymentController.java
  src/main/java/com/nineteen/omp/payment/service/PaymentService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentServiceImpl.java
Labels: feat

#22 Feat/create pageable utils
  src/main/java/com/nineteen/omp/global/common/PageSize.java
  src/main/java/com/nineteen/omp/global/common/PageSortBy.java
  src/main/java/com/nineteen/omp/global/exception/CommonExceptionCode.java
  src/main/java/com/nineteen/omp/global/utils/PageableUtils.java
Labels: feat

#27 Feat/payments
  build.gradle
  src/main/java/com/nineteen/omp/global/common/PageSize.java
  src/main/java/com/nineteen/omp/global/common/PageSortBy.java
  src/main/java/com/nineteen/omp/global/exception/CommonExceptionCode.java
  src/main/java/com/nineteen/omp/global/utils/PageableUtils.java
  src/main/java/com/nineteen/omp/payment/controller/PaymentController.java
  src/main/java/com/nineteen/omp/payment/controller/dto/CreatePaymentRequestDto.java
Labels: feat

#28 Feat/get user by user
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/controller/dto/GetUserInfoResponseDto.java
  src/main/java/com/nineteen/omp/user/domain/UserExceptionCode.java
  src/main/java/com/nineteen/omp/user/repository/UserRepository.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
  src/main/java/com/nineteen/omp/user/service/dto/GetUserInfoResponseCommand.java
  src/test/java/com/nineteen/omp/user/service/UserServiceImplTest.java
Labels: feat

#29 Feat/get users all
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/controller/dto/GetUserInfoPageResponseDto.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
  src/main/java/com/nineteen/omp/user/service/dto/GetUserInfoPageResponseCommand.java
  src/test/java/com/nineteen/omp/user/service/UserServiceImplTest.java
Labels: feat

#31 Feat/update user info
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/controller/dto/UpdateUserRequestDto.java
  src/main/java/com/nineteen/omp/user/domain/User.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
  src/main/java/com/nineteen/omp/user/service/dto/UpdateUserRequestCommand.java
  src/test/java/com/nineteen/omp/user/service/UserServiceImplTest.java
Labels: feat

#35 Feat/search users by nickname
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/repository/UserRepository.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
  src/test/java/com/nineteen/omp/user/repository/UserRepositoryTest.java
  src/test/java/com/nineteen/omp/user/service/UserServiceImplTest.java
Labels: feat

#36 Feat/users
  src/main/java/com/nineteen/omp/global/entity/BaseEntity.java
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/controller/dto/GetUserInfoPageResponseDto.java
  src/main/java/com/nineteen/omp/user/controller/dto/GetUserInfoResponseDto.java
  src/main/java/com/nineteen/omp/user/controller/dto/UpdateUserRequestDto.java
  src/main/java/com/nineteen/omp/user/domain/User.java
  src/main/java/com/nineteen/omp/user/repository/UserRepository.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
  src/main/java/com/nineteen/omp/user/service/dto/GetUserInfoPageResponseCommand.java
  src/main/java/com/nineteen/omp/user/service/dto/GetUserInfoResponseCommand.java
  src/main/java/com/nineteen/omp/user/service/dto/UpdateUserRequestCommand.java
  src/test/java/com/nineteen/omp/global/entity/BaseEntityTest.java
  src/test/java/com/nineteen/omp/user/repository/UserRepositoryTest.java
  src/test/java/com/nineteen/omp/user/service/UserServiceImplTest.java
Labels: feat

#47 Feat/apply auditing xxby
  src/main/java/com/nineteen/omp/global/config/JpaAuditingConfig.java
  src/main/java/com/nineteen/omp/global/entity/BaseEntity.java
  src/test/java/com/nineteen/omp/global/entity/BaseEntityTest.java
Labels: feat

#50 Feat/create user cruds
  build.gradle
  src/main/java/com/nineteen/omp/auth/config/SecurityConfig.java
  src/main/java/com/nineteen/omp/auth/controller/AuthController.java
  src/main/java/com/nineteen/omp/auth/domain/Role.java
  src/main/java/com/nineteen/omp/auth/dto/UserDetailsImpl.java
  src/main/java/com/nineteen/omp/auth/exception/AuthExceptionCode.java
  src/main/java/com/nineteen/omp/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nineteen/omp/auth/filter/JwtFilter.java
  src/main/java/com/nineteen/omp/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/nineteen/omp/auth/jwt/JwtHeaderHandler.java
  src/main/java/com/nineteen/omp/auth/jwt/JwtProvider.java
  src/main/java/com/nineteen/omp/auth/jwt/entity/RefreshToken.java
  src/main/java/com/nineteen/omp/auth/jwt/enums/JwtClaims.java
  src/main/java/com/nineteen/omp/auth/jwt/repository/RefreshRepository.java
  src/main/java/com/nineteen/omp/auth/jwt/service/RefreshService.java
  src/main/java/com/nineteen/omp/auth/jwt/service/RefreshServiceImpl.java
  src/main/java/com/nineteen/omp/auth/service/AuthService.java
  src/main/java/com/nineteen/omp/auth/service/AuthServiceImpl.java
  src/main/java/com/nineteen/omp/global/config/EmbeddedRedisConfig.java
  src/main/java/com/nineteen/omp/global/config/JpaAuditingConfig.java
  src/main/java/com/nineteen/omp/global/config/RedisConfig.java
  src/main/java/com/nineteen/omp/global/entity/BaseEntity.java
  src/main/java/com/nineteen/omp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nineteen/omp/global/utils/AesEncryptor.java
  src/main/java/com/nineteen/omp/global/utils/Encryptor.java
  src/main/java/com/nineteen/omp/user/controller/UserController.java
  src/main/java/com/nineteen/omp/user/controller/dto/GetUserInfoPageResponseDto.java
  src/main/java/com/nineteen/omp/user/controller/dto/GetUserInfoResponseDto.java
  src/main/java/com/nineteen/omp/user/controller/dto/LoginRequestDto.java
  src/main/java/com/nineteen/omp/user/controller/dto/SignupRequestDto.java
  src/main/java/com/nineteen/omp/user/controller/dto/UpdateUserRequestDto.java
  src/main/java/com/nineteen/omp/user/domain/User.java
  src/main/java/com/nineteen/omp/user/exception/UserExceptionCode.java
  src/main/java/com/nineteen/omp/user/repository/UserRepository.java
  src/main/java/com/nineteen/omp/user/service/UserDetailsServiceImpl.java
  src/main/java/com/nineteen/omp/user/service/UserService.java
  src/main/java/com/nineteen/omp/user/service/UserServiceImpl.java
  src/main/java/com/nineteen/omp/user/service/dto/GetUserInfoPageResponseCommand.java
  src/main/java/com/nineteen/omp/user/service/dto/GetUserInfoResponseCommand.java
  src/main/java/com/nineteen/omp/user/service/dto/UpdateUserRequestCommand.java
  src/test/java/com/nineteen/omp/auth/filter/JwtFilterTest.java
  src/test/java/com/nineteen/omp/auth/handler/CustomAuthenticationSuccessHandlerTest.java
  src/test/java/com/nineteen/omp/auth/jwt/JwtProviderTest.java
  src/test/java/com/nineteen/omp/auth/jwt/repository/RefreshRepositoryTest.java
  src/test/java/com/nineteen/omp/auth/service/AuthServiceImplTest.java
  src/test/java/com/nineteen/omp/global/entity/BaseEntityTest.java
  src/test/java/com/nineteen/omp/user/repository/UserRepositoryTest.java
  src/test/java/com/nineteen/omp/user/service/UserServiceImplTest.java
Labels: feat

#69 Feat/add payments
  src/main/java/com/nineteen/omp/auth/dto/UserDetailsImpl.java
  src/main/java/com/nineteen/omp/order/domain/Order.java
  src/main/java/com/nineteen/omp/payment/controller/PaymentController.java
  src/main/java/com/nineteen/omp/payment/controller/dto/GetPaymentResponseDto.java
  src/main/java/com/nineteen/omp/payment/domain/Payment.java
  src/main/java/com/nineteen/omp/payment/domain/PaymentStatus.java
  src/main/java/com/nineteen/omp/payment/exception/PaymentExceptionCode.java
  src/main/java/com/nineteen/omp/payment/repository/PaymentRepository.java
  src/main/java/com/nineteen/omp/payment/service/DummyPaymentGatewayService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentGatewayService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentService.java
  src/main/java/com/nineteen/omp/payment/service/PaymentServiceImpl.java
  src/main/java/com/nineteen/omp/payment/service/dto/ExecutePaymentRequestCommand.java
  src/main/java/com/nineteen/omp/payment/service/dto/ExecutePaymentResponseCommand.java
  src/main/java/com/nineteen/omp/payment/service/dto/GetPaymentResponseCommand.java
  src/main/java/com/nineteen/omp/store/repository/StoreRepository.java
  src/test/java/com/nineteen/omp/fixture/FixtureFactory.java
  src/test/java/com/nineteen/omp/payment/repository/PaymentRepositoryTest.java
  src/test/java/com/nineteen/omp/payment/service/PaymentServiceImplTest.java
Labels: feat

#70 feat(UserController): 사용자 id 값 노출 삭제
  src/main/java/com/nineteen/omp/user/controller/UserController.java
Labels: feat

#71 Feat/refact coupon
  src/main/java/com/nineteen/omp/coupon/controller/CouponController.java
  src/main/java/com/nineteen/omp/coupon/controller/UserCouponController.java
  src/main/java/com/nineteen/omp/coupon/controller/dto/UserCouponResponseDto.java
  src/main/java/com/nineteen/omp/coupon/repository/UserCouponRepository.java
  src/main/java/com/nineteen/omp/coupon/service/CouponServiceImpl.java
  src/main/java/com/nineteen/omp/coupon/service/UserCouponService.java
  src/main/java/com/nineteen/omp/coupon/service/UserCouponServiceImpl.java
Labels: feat

#84 feat/ apply github actions cicd
  .github/workflows/cicd.yaml
  Dockerfile
Labels: feat
